"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.structuredRows = exports.languageFromPath = exports.diffLines = exports.highlightInWorkerBatch = exports.highlightInWorker = exports.defaultWorkerPoolSize = exports.createWebWorkerPool = exports.computeDiffInWorkerStream = exports.computeDiffInWorker = exports.UnifiedDiffView = exports.SplitDiffView = exports.buildSplitRows = void 0;
var SplitDiffView_1 = require("./components/SplitDiffView");
Object.defineProperty(exports, "buildSplitRows", { enumerable: true, get: function () { return SplitDiffView_1.buildSplitRows; } });
Object.defineProperty(exports, "SplitDiffView", { enumerable: true, get: function () { return SplitDiffView_1.SplitDiffView; } });
var UnifiedDiffView_1 = require("./components/UnifiedDiffView");
Object.defineProperty(exports, "UnifiedDiffView", { enumerable: true, get: function () { return UnifiedDiffView_1.UnifiedDiffView; } });
var diff_client_1 = require("./components/diff-client");
Object.defineProperty(exports, "computeDiffInWorker", { enumerable: true, get: function () { return diff_client_1.computeDiffInWorker; } });
Object.defineProperty(exports, "computeDiffInWorkerStream", { enumerable: true, get: function () { return diff_client_1.computeDiffInWorkerStream; } });
var worker_pool_1 = require("./components/worker-pool");
Object.defineProperty(exports, "createWebWorkerPool", { enumerable: true, get: function () { return worker_pool_1.createWebWorkerPool; } });
Object.defineProperty(exports, "defaultWorkerPoolSize", { enumerable: true, get: function () { return worker_pool_1.defaultWorkerPoolSize; } });
var syntax_client_1 = require("./components/syntax-client");
Object.defineProperty(exports, "highlightInWorker", { enumerable: true, get: function () { return syntax_client_1.highlightInWorker; } });
Object.defineProperty(exports, "highlightInWorkerBatch", { enumerable: true, get: function () { return syntax_client_1.highlightInWorkerBatch; } });
var diff_utils_1 = require("./diff-utils");
Object.defineProperty(exports, "diffLines", { enumerable: true, get: function () { return diff_utils_1.diffLines; } });
Object.defineProperty(exports, "languageFromPath", { enumerable: true, get: function () { return diff_utils_1.languageFromPath; } });
Object.defineProperty(exports, "structuredRows", { enumerable: true, get: function () { return diff_utils_1.structuredRows; } });
