import type { PluginManifest } from "@natalia/plugin";

// Prettier would expand this static data beyond the source-size guard.
// prettier-ignore
export const PRODUCT_PLUGIN_MANIFESTS: Record<string, PluginManifest> = {
  "natalia-attachment": {
    apiVersion: 2,
    id: "natalia-attachment",
    version: "1.0.0",
    name: "Attachment",
    description: "Durable local attachment storage and materialization.",
    entry: "natalia:attachment",
    scope: "workspace",
    provides: ["attachment.service"],
    requires: [],
    optionalRequires: [],
    conflicts: [],
    dependencies: [],
    hooks: {},
    integrationPoints: ["services"],
  },
  "natalia-checkpoint": {
    apiVersion: 2,
    id: "natalia-checkpoint",
    version: "1.0.0",
    name: "Checkpoint",
    description: "Durable session checkpoints and rollback.",
    entry: "natalia:checkpoint",
    scope: "workspace",
    provides: ["checkpoint.factory"],
    requires: [],
    optionalRequires: [],
    conflicts: [],
    dependencies: [],
    hooks: {},
    integrationPoints: ["services", "commands"],
  },
  "natalia-collaboration": {
    apiVersion: 2,
    id: "natalia-collaboration",
    version: "1.0.0",
    name: "Collaboration",
    description: "Interactive waiting and Live Work Chat collaboration.",
    entry: "natalia:collaboration",
    scope: "workspace",
    provides: ["collaboration.waiter"],
    requires: [],
    optionalRequires: [],
    conflicts: [],
    dependencies: [],
    hooks: {},
    integrationPoints: ["services", "tools"],
  },
  "natalia-compaction": {
    apiVersion: 2,
    id: "natalia-compaction",
    version: "1.0.0",
    name: "Compaction",
    description: "Context compaction and context-limit recovery.",
    entry: "natalia:compaction",
    scope: "workspace",
    provides: ["compaction.service"],
    requires: ["retry.service", "context-ledger.factory"],
    optionalRequires: [],
    conflicts: [],
    dependencies: [
      { id: "natalia-retry", spec: ">=1.0.0", optional: false, peer: false },
      {
        id: "natalia-context-ledger",
        spec: ">=1.0.0",
        optional: false,
        peer: false,
      },
    ],
    hooks: {},
    integrationPoints: ["services"],
  },
  "natalia-context-ledger": {
    apiVersion: 2,
    id: "natalia-context-ledger",
    version: "1.0.0",
    name: "Context Ledger",
    description: "Context ledger construction and durable event recovery.",
    entry: "natalia:context-ledger",
    scope: "workspace",
    provides: ["context-ledger.factory"],
    requires: [],
    optionalRequires: [],
    conflicts: [],
    dependencies: [],
    hooks: {},
    integrationPoints: ["services"],
  },
  "natalia-governance-ledger": {
    apiVersion: 2,
    id: "natalia-governance-ledger",
    version: "1.0.0",
    name: "Governance Ledger",
    description: "Constitution, decision, evidence and completion writers.",
    entry: "natalia:governance-ledger",
    scope: "workspace",
    provides: ["governance-ledger.controller"],
    requires: ["work-ledger.controller"],
    optionalRequires: [],
    conflicts: [],
    dependencies: [
      {
        id: "natalia-work-ledger",
        spec: ">=1.0.0",
        optional: false,
        peer: false,
      },
    ],
    hooks: {},
    integrationPoints: ["services"],
  },
  "natalia-local-tools": {
    apiVersion: 2,
    id: "natalia-local-tools",
    version: "1.0.0",
    name: "Local Tools",
    description: "Out-of-tree tool families discovered in configured paths.",
    entry: "natalia:local-tools",
    scope: "workspace",
    provides: ["localTools.reload"],
    requires: [],
    optionalRequires: [],
    conflicts: [],
    dependencies: [],
    hooks: {},
    integrationPoints: ["tools", "services"],
  },
  "natalia-mcp": {
    apiVersion: 2,
    id: "natalia-mcp",
    version: "1.0.0",
    name: "MCP Server",
    description: "Native MCP connections and their tools.",
    entry: "natalia:mcp",
    scope: "session",
    provides: ["mcp.service"],
    requires: [],
    optionalRequires: [],
    conflicts: [],
    dependencies: [],
    hooks: {},
    integrationPoints: ["tools", "services"],
  },
  "natalia-provider-model": {
    apiVersion: 2,
    id: "natalia-provider-model",
    version: "1.0.0",
    name: "Provider Model",
    description:
      "Provider/model selection, the main agent loop and Live Work Chat lifecycle.",
    entry: "natalia:provider-model",
    scope: "workspace",
    provides: ["provider-model.controller"],
    requires: ["retry.service", "attachment.service", "compaction.service"],
    optionalRequires: [],
    conflicts: [],
    dependencies: [
      { id: "natalia-retry", spec: ">=1.0.0", optional: false, peer: false },
      {
        id: "natalia-attachment",
        spec: ">=1.0.0",
        optional: false,
        peer: false,
      },
      {
        id: "natalia-compaction",
        spec: ">=1.0.0",
        optional: false,
        peer: false,
      },
    ],
    hooks: {},
    integrationPoints: ["services", "commands"],
  },
  "natalia-retry": {
    apiVersion: 2,
    id: "natalia-retry",
    version: "1.0.0",
    name: "Retry",
    description: "Provider retry policy and execution lifecycle.",
    entry: "natalia:retry",
    scope: "workspace",
    provides: ["retry.service"],
    requires: [],
    optionalRequires: [],
    conflicts: [],
    dependencies: [],
    hooks: {},
    integrationPoints: ["services"],
  },
  "natalia-runtime-config": {
    apiVersion: 2,
    id: "natalia-runtime-config",
    version: "1.0.0",
    name: "Runtime Config",
    description: "The runtime's effective config, refreshed on reload.",
    entry: "natalia:runtime-config",
    scope: "workspace",
    provides: ["runtime.config"],
    requires: [],
    optionalRequires: [],
    conflicts: [],
    dependencies: [],
    hooks: {},
    integrationPoints: ["services"],
  },
  "natalia-runtime-ui": {
    apiVersion: 2,
    id: "natalia-runtime-ui",
    version: "1.0.0",
    name: "Runtime UI",
    description: "Shared runtime status projection for interface adapters.",
    entry: "natalia:runtime-ui",
    scope: "workspace",
    provides: ["status.snapshot.controller"],
    requires: [],
    optionalRequires: [],
    conflicts: [],
    dependencies: [],
    hooks: {},
    integrationPoints: ["services", "commands"],
  },
  "natalia-sandbox": {
    apiVersion: 2,
    id: "natalia-sandbox",
    version: "1.0.0",
    name: "Sandbox",
    description: "Isolated workspaces for subagents and experiments.",
    entry: "natalia:sandbox",
    scope: "workspace",
    provides: ["sandbox.service"],
    requires: [],
    optionalRequires: [],
    conflicts: [],
    dependencies: [],
    hooks: {},
    integrationPoints: ["services"],
  },
  "natalia-session-store": {
    apiVersion: 2,
    id: "natalia-session-store",
    version: "1.0.0",
    name: "Session Store",
    description: "Durable session persistence.",
    entry: "natalia:session-store",
    scope: "workspace",
    provides: ["session-store.controller"],
    requires: ["attachment.service"],
    optionalRequires: [],
    conflicts: [],
    dependencies: [
      {
        id: "natalia-attachment",
        spec: ">=1.0.0",
        optional: false,
        peer: false,
      },
    ],
    hooks: {},
    integrationPoints: ["services", "commands"],
  },
  "natalia-skills": {
    apiVersion: 1,
    id: "natalia-skills",
    version: "1.0.0",
    name: "Skills",
    description: "Discovered project, user and remote skills.",
    entry: "natalia:skills",
    capabilities: ["tools", "commands"],
    scope: "workspace",
    provides: ["skills.service"],
    requires: [],
  },
  "natalia-subagents": {
    apiVersion: 2,
    id: "natalia-subagents",
    version: "1.0.0",
    name: "Subagents",
    description: "Delegated work to sub-agents.",
    entry: "natalia:subagents",
    scope: "workspace",
    provides: ["subagents.service"],
    requires: [],
    optionalRequires: [],
    conflicts: [],
    dependencies: [],
    hooks: {},
    integrationPoints: ["services"],
  },
  "natalia-task-module": {
    apiVersion: 2,
    id: "natalia-task-module",
    version: "1.0.0",
    name: "Task Module",
    description:
      "Task-scoped tools for the active flow module: completion claims, issue reporting and incremental data source reads.",
    entry: "natalia:task-module",
    scope: "session",
    provides: [],
    requires: [],
    optionalRequires: [],
    conflicts: [],
    dependencies: [],
    hooks: {},
    integrationPoints: ["tools"],
  },
  "natalia-task-workflow": {
    apiVersion: 2,
    id: "natalia-task-workflow",
    version: "1.0.0",
    name: "Task Workflow",
    description: "Task and workflow documents, preflight and scheduling.",
    entry: "natalia:task-workflow",
    scope: "workspace",
    provides: ["task-workflow.controller"],
    requires: [],
    optionalRequires: [],
    conflicts: [],
    dependencies: [],
    hooks: {},
    integrationPoints: ["services"],
  },
  "natalia-team": {
    apiVersion: 2,
    id: "natalia-team",
    version: "1.0.0",
    name: "Team",
    description:
      "Parallel fan-out of sandboxed subagents and the lead reviewer's merge.",
    entry: "natalia:team",
    scope: "workspace",
    provides: ["team.behavior"],
    requires: ["subagents.service", "sandbox.service"],
    optionalRequires: [],
    conflicts: [],
    dependencies: [
      {
        id: "natalia-subagents",
        spec: "workspace:*",
        optional: false,
        peer: false,
      },
      {
        id: "natalia-sandbox",
        spec: "workspace:*",
        optional: false,
        peer: false,
      },
    ],
    hooks: {},
    integrationPoints: ["tools", "services"],
  },
  "natalia-terminal": { apiVersion: 2, id: "natalia-terminal", version: "1.0.0", name: "Terminal", description: "Native terminal panes and interactive programs.", entry: "natalia:terminal", scope: "session", provides: ["terminal.controller"], requires: [], optionalRequires: [], conflicts: [], dependencies: [], hooks: {}, integrationPoints: ["services"] },
  "natalia-tool-pipeline": { apiVersion: 2, id: "natalia-tool-pipeline", version: "1.0.0", name: "Tool Pipeline", description: "The single policy funnel every tool call passes through.", entry: "natalia:tool-pipeline", scope: "workspace", provides: ["tool.policy"], requires: [], optionalRequires: [], conflicts: [], dependencies: [], hooks: {}, integrationPoints: ["services"] },
  "natalia-turn-orchestration": {
    apiVersion: 2,
    id: "natalia-turn-orchestration",
    version: "1.0.0",
    name: "Turn Orchestration",
    description: "Durable turn admission, promotion and dispatch ordering.",
    entry: "natalia:turn-orchestration",
    scope: "workspace",
    provides: ["turn.controller"],
    requires: ["session-store.controller"],
    optionalRequires: [],
    conflicts: [],
    dependencies: [
      {
        id: "natalia-session-store",
        spec: ">=1.0.0",
        optional: false,
        peer: false,
      },
    ],
    hooks: {},
    integrationPoints: ["services"],
  },
  "natalia-work-ledger": { apiVersion: 2, id: "natalia-work-ledger", version: "1.0.0", name: "Work Ledger", description: "Plan, drift and work graph event writers.", entry: "natalia:work-ledger", scope: "workspace", provides: ["work-ledger.controller"], requires: [], optionalRequires: [], conflicts: [], dependencies: [], hooks: {}, integrationPoints: ["services"] },
  "natalia-workspace": { apiVersion: 2, id: "natalia-workspace", version: "1.0.0", name: "Workspace", description: "Workspace observation, write serialisation and mutation attribution.", entry: "natalia:workspace", scope: "workspace", provides: ["workspace.writeLock", "workspace.mutations", "workspace.files"], requires: [], optionalRequires: [], conflicts: [], dependencies: [], hooks: {}, integrationPoints: ["services", "commands"] },
};
