"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.storeLocalAttachments = exports.storeLocalAttachmentBytes = exports.referencedAttachmentsForSessions = exports.isTextAttachment = exports.cleanupUnreferencedAttachments = exports.attachmentText = exports.attachmentDataURL = exports.DEFAULT_ATTACHMENT_LIMITS = exports.scaleImage = exports.DEFAULT_MAX_IMAGE_LONG_EDGE = exports.createAttachmentService = exports.attachmentService = void 0;
var service_token_1 = require("./service-token");
Object.defineProperty(exports, "attachmentService", { enumerable: true, get: function () { return service_token_1.attachmentService; } });
var attachment_service_1 = require("./attachment-service");
Object.defineProperty(exports, "createAttachmentService", { enumerable: true, get: function () { return attachment_service_1.createAttachmentService; } });
var image_scale_1 = require("./image-scale");
Object.defineProperty(exports, "DEFAULT_MAX_IMAGE_LONG_EDGE", { enumerable: true, get: function () { return image_scale_1.DEFAULT_MAX_IMAGE_LONG_EDGE; } });
Object.defineProperty(exports, "scaleImage", { enumerable: true, get: function () { return image_scale_1.scaleImage; } });
var attachments_1 = require("./attachments");
Object.defineProperty(exports, "DEFAULT_ATTACHMENT_LIMITS", { enumerable: true, get: function () { return attachments_1.DEFAULT_ATTACHMENT_LIMITS; } });
Object.defineProperty(exports, "attachmentDataURL", { enumerable: true, get: function () { return attachments_1.attachmentDataURL; } });
Object.defineProperty(exports, "attachmentText", { enumerable: true, get: function () { return attachments_1.attachmentText; } });
Object.defineProperty(exports, "cleanupUnreferencedAttachments", { enumerable: true, get: function () { return attachments_1.cleanupUnreferencedAttachments; } });
Object.defineProperty(exports, "isTextAttachment", { enumerable: true, get: function () { return attachments_1.isTextAttachment; } });
Object.defineProperty(exports, "referencedAttachmentsForSessions", { enumerable: true, get: function () { return attachments_1.referencedAttachmentsForSessions; } });
Object.defineProperty(exports, "storeLocalAttachmentBytes", { enumerable: true, get: function () { return attachments_1.storeLocalAttachmentBytes; } });
Object.defineProperty(exports, "storeLocalAttachments", { enumerable: true, get: function () { return attachments_1.storeLocalAttachments; } });
