"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.initialTailScrollState = exports.evaluateTailScroll = exports.renderMarkdownHtml = exports.PendingPanel = exports.PendingList = exports.PendingDetail = exports.PendingBadge = exports.cssVar = exports.defineUiShellLayoutPlugin = exports.defineUiSkin = exports.defineUiLayoutProfile = exports.applyUiSkin = exports.PagedTranscriptController = exports.TailScrollController = exports.duplicateVirtualIndexes = exports.duplicateValues = exports.dedupeVirtualItems = exports.ContextMeter = exports.fixedRowHeight = exports.estimateMessageHeight = exports.MessageRow = exports.Transcript = exports.contextMenuStyles = exports.ContextMenu = void 0;
var context_menu_1 = require("./context-menu");
Object.defineProperty(exports, "ContextMenu", { enumerable: true, get: function () { return context_menu_1.ContextMenu; } });
Object.defineProperty(exports, "contextMenuStyles", { enumerable: true, get: function () { return context_menu_1.contextMenuStyles; } });
var transcript_1 = require("./transcript");
Object.defineProperty(exports, "Transcript", { enumerable: true, get: function () { return transcript_1.Transcript; } });
Object.defineProperty(exports, "MessageRow", { enumerable: true, get: function () { return transcript_1.MessageRow; } });
Object.defineProperty(exports, "estimateMessageHeight", { enumerable: true, get: function () { return transcript_1.estimateMessageHeight; } });
Object.defineProperty(exports, "fixedRowHeight", { enumerable: true, get: function () { return transcript_1.fixedRowHeight; } });
var context_meter_1 = require("./context-meter");
Object.defineProperty(exports, "ContextMeter", { enumerable: true, get: function () { return context_meter_1.ContextMeter; } });
var virtual_items_1 = require("./virtual-items");
Object.defineProperty(exports, "dedupeVirtualItems", { enumerable: true, get: function () { return virtual_items_1.dedupeVirtualItems; } });
Object.defineProperty(exports, "duplicateValues", { enumerable: true, get: function () { return virtual_items_1.duplicateValues; } });
Object.defineProperty(exports, "duplicateVirtualIndexes", { enumerable: true, get: function () { return virtual_items_1.duplicateVirtualIndexes; } });
var scroll_controller_1 = require("./scroll-controller");
Object.defineProperty(exports, "TailScrollController", { enumerable: true, get: function () { return scroll_controller_1.TailScrollController; } });
var paged_transcript_1 = require("./paged-transcript");
Object.defineProperty(exports, "PagedTranscriptController", { enumerable: true, get: function () { return paged_transcript_1.PagedTranscriptController; } });
var skin_1 = require("./skin");
Object.defineProperty(exports, "applyUiSkin", { enumerable: true, get: function () { return skin_1.applyUiSkin; } });
Object.defineProperty(exports, "defineUiLayoutProfile", { enumerable: true, get: function () { return skin_1.defineUiLayoutProfile; } });
Object.defineProperty(exports, "defineUiSkin", { enumerable: true, get: function () { return skin_1.defineUiSkin; } });
var skin_2 = require("./skin");
Object.defineProperty(exports, "defineUiShellLayoutPlugin", { enumerable: true, get: function () { return skin_2.defineUiShellLayoutPlugin; } });
var css_vars_1 = require("./css-vars");
Object.defineProperty(exports, "cssVar", { enumerable: true, get: function () { return css_vars_1.cssVar; } });
var pending_1 = require("./pending");
Object.defineProperty(exports, "PendingBadge", { enumerable: true, get: function () { return pending_1.PendingBadge; } });
Object.defineProperty(exports, "PendingDetail", { enumerable: true, get: function () { return pending_1.PendingDetail; } });
Object.defineProperty(exports, "PendingList", { enumerable: true, get: function () { return pending_1.PendingList; } });
Object.defineProperty(exports, "PendingPanel", { enumerable: true, get: function () { return pending_1.PendingPanel; } });
var markdown_1 = require("./markdown");
Object.defineProperty(exports, "renderMarkdownHtml", { enumerable: true, get: function () { return markdown_1.renderMarkdownHtml; } });
var tail_scroll_machine_1 = require("./tail-scroll-machine");
Object.defineProperty(exports, "evaluateTailScroll", { enumerable: true, get: function () { return tail_scroll_machine_1.evaluateTailScroll; } });
Object.defineProperty(exports, "initialTailScrollState", { enumerable: true, get: function () { return tail_scroll_machine_1.initialTailScrollState; } });
