import type { CompositionRowRegistration } from "./profile";

/**
 * spec §6.5 — `composition.d.ts` codegen: the registry IS the input
 * (each registration declares its row id, its impl id set, and the
 * schema REF its config type derives from). The file serves drop-in
 * authors: every legal row id, impl literal and config type in one
 * place, each property annotated with its ORIGIN (nixpkgs
 * `declarations`' analogue) — so an editor completes a
 * `~/.natalia/composition.d/*.json` against exactly what the loader
 * will accept.
 *
 * The config type is `z.input<typeof schema>`: what an AUTHOR may
 * write (fields with defaults may be omitted — the loader applies
 * them), which is the authoring-facing twin of the spec's z.infer
 * (what the loader holds AFTER defaults). Deriving from the schema's
 * import — not re-spelling it — is what makes drift impossible.
 */

const SCHEMA_LITERAL = '"natalia.composition-profile/1"';

function typeAliasFor(rowID: string): string {
  const withoutNamespace = rowID.replace(
    /^(anthelia\.|natalia\.|plugin:|facet:)/u,
    "",
  );
  const words = withoutNamespace.split(/[.\-_:]/u).filter(Boolean);
  const pascal = words
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("");
  return pascal || "Row";
}

function emitImpl(registration: CompositionRowRegistration): string {
  if (!registration.implIDs.length)
    return "  /** Selectable impls: none — the backend is discovered at runtime, not selected (§6.1). */\n  impl?: never;";
  const literals = registration.implIDs
    .map((id) => JSON.stringify(id))
    .join(" | ");
  return `  impl?: ${literals};`;
}

export function generateCompositionDts(
  registrations: readonly CompositionRowRegistration[],
): string {
  const sorted = [...registrations].sort((a, b) =>
    a.rowID.localeCompare(b.rowID),
  );
  const refs = [
    ...new Set(
      sorted
        .map((registration) => registration.configSchemaRef)
        .filter((ref): ref is NonNullable<typeof ref> => Boolean(ref))
        .map((ref) => `${ref.from}\u0000${ref.name}`),
    ),
  ];
  const lines: string[] = [
    "// GENERATED by scripts/composition-dts.ts — DO NOT EDIT BY HAND.",
    "// Freshness gate: packages/core/composition/test/dts-freshness.test.ts",
    "// turns red when the row registry outgrows this file — regenerate with",
    "// `npm run codegen:composition-dts`.",
    "//",
    "// The editor's view of a composition drop-in file:",
    "//   ~/.natalia/composition.d/*.json  and  <ws>/.natalia/composition.d/*.json",
    "// Each row documents its ORIGIN (which schema its config derives from),",
    "// the declarations-file convention from nixpkgs (spec §6.5).",
    "",
    'import type { z } from "zod";',
  ];
  for (const key of refs) {
    const [from, name] = key.split("\u0000");
    lines.push(`import type { ${name} } from "${from}";`);
  }
  lines.push(
    "",
    `export type CompositionProfileSchema = ${SCHEMA_LITERAL};`,
    "",
    "/** The union a drop-in file's `rows` array accepts — discriminated by id. */",
    `export type CompositionRow =${sorted.length ? "" : " never;"}`,
  );
  const rowTypes: string[] = [];
  for (const registration of sorted) {
    const alias = typeAliasFor(registration.rowID);
    const ref = registration.configSchemaRef;
    const config = ref
      ? `z.input<typeof ${ref.name}>`
      : "unknown /* no configSchemaRef declared */";
    const origin = ref
      ? `origin: registry — ${ref.from}.${ref.name}`
      : "origin: registry (no schema ref declared)";
    rowTypes.push(
      ...[
        "",
        `/** ${origin} */`,
        `export type ${alias} = {`,
        `  id: ${JSON.stringify(registration.rowID)};`,
        emitImpl(registration),
        "  disabled?: boolean;",
        `  config?: ${config};`,
        "};",
      ],
    );
    // extend the union row by row
    lines[lines.length - 1] += ` | ${alias}`;
    rowTypes.pop();
    // push the type body AFTER the union header (built below)
    lines.push(
      "",
      `/** ${origin} */`,
      `export type ${alias} = {`,
      `  id: ${JSON.stringify(registration.rowID)};`,
      emitImpl(registration),
      "  disabled?: boolean;",
      `  config?: ${config};`,
      "};",
    );
  }
  lines.push(
    "",
    "/** The envelope every profile file (base + drop-ins) carries. */",
    "export type CompositionProfileEnvelope = {",
    "  schema: CompositionProfileSchema;",
    "  rows: CompositionRow[];",
    "};",
    "",
  );
  return lines.join("\n");
}
