// GENERATED by scripts/composition-dts.ts — DO NOT EDIT BY HAND.
// Freshness gate: packages/core/composition/test/dts-freshness.test.ts
// turns red when the row registry outgrows this file — regenerate with
// `npm run codegen:composition-dts`.
//
// The editor's view of a composition drop-in file:
//   ~/.natalia/composition.d/*.json  and  <ws>/.natalia/composition.d/*.json
// Each row documents its ORIGIN (which schema its config derives from),
// the declarations-file convention from nixpkgs (spec §6.5).

import type { z } from "zod";
import type { responseCacheConfigSchema } from "@anthelia/contracts";
import type { objectStoreConfigSchema } from "@anthelia/contracts";
import type { confinementConfigSchema } from "@anthelia/contracts";

export type CompositionProfileSchema = "natalia.composition-profile/1";

/** The union a drop-in file's `rows` array accepts — discriminated by id. */
export type CompositionRow = CacheResponse | Objectstore | Sandbox;

/** origin: registry — @anthelia/contracts.responseCacheConfigSchema */
export type CacheResponse = {
  id: "anthelia.cache.response";
  /** Selectable impls: none — the backend is discovered at runtime, not selected (§6.1). */
  impl?: never;
  disabled?: boolean;
  config?: z.input<typeof responseCacheConfigSchema>;
};

/** origin: registry — @anthelia/contracts.objectStoreConfigSchema */
export type Objectstore = {
  id: "anthelia.objectstore";
  impl?: "typescript" | "rust";
  disabled?: boolean;
  config?: z.input<typeof objectStoreConfigSchema>;
};

/** origin: registry — @anthelia/contracts.confinementConfigSchema */
export type Sandbox = {
  id: "anthelia.sandbox";
  /** Selectable impls: none — the backend is discovered at runtime, not selected (§6.1). */
  impl?: never;
  disabled?: boolean;
  config?: z.input<typeof confinementConfigSchema>;
};

/** The envelope every profile file (base + drop-ins) carries. */
export type CompositionProfileEnvelope = {
  schema: CompositionProfileSchema;
  rows: CompositionRow[];
};
