"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.updateGlobalConfig = exports.updateConfigAtScope = exports.updateConfig = exports.migrateProjectModelConfigToGlobal = exports.resolveConfig = exports.GLOBAL_MODEL_CONFIG_KEYS = exports.defaultGlobalConfigPath = exports.configPatch = void 0;
var service_merge_1 = require("./service-merge");
Object.defineProperty(exports, "configPatch", { enumerable: true, get: function () { return service_merge_1.configPatch; } });
var service_resolution_1 = require("./service-resolution");
Object.defineProperty(exports, "defaultGlobalConfigPath", { enumerable: true, get: function () { return service_resolution_1.defaultGlobalConfigPath; } });
Object.defineProperty(exports, "GLOBAL_MODEL_CONFIG_KEYS", { enumerable: true, get: function () { return service_resolution_1.GLOBAL_MODEL_CONFIG_KEYS; } });
Object.defineProperty(exports, "resolveConfig", { enumerable: true, get: function () { return service_resolution_1.resolveConfig; } });
var service_write_1 = require("./service-write");
Object.defineProperty(exports, "migrateProjectModelConfigToGlobal", { enumerable: true, get: function () { return service_write_1.migrateProjectModelConfigToGlobal; } });
Object.defineProperty(exports, "updateConfig", { enumerable: true, get: function () { return service_write_1.updateConfig; } });
Object.defineProperty(exports, "updateConfigAtScope", { enumerable: true, get: function () { return service_write_1.updateConfigAtScope; } });
Object.defineProperty(exports, "updateGlobalConfig", { enumerable: true, get: function () { return service_write_1.updateGlobalConfig; } });
