use tree_sitter::Language;

pub fn grammar(language_id: &str) -> Option<Language> {
    match language_id {
        "javascript" | "js" => Some(tree_sitter_javascript::LANGUAGE.into()),
        "typescript" | "ts" => Some(tree_sitter_typescript::LANGUAGE_TYPESCRIPT.into()),
        "tsx" => Some(tree_sitter_typescript::LANGUAGE_TSX.into()),
        "python" | "py" => Some(tree_sitter_python::LANGUAGE.into()),
        "go" => Some(tree_sitter_go::LANGUAGE.into()),
        "rust" | "rs" => Some(tree_sitter_rust_orchard::LANGUAGE.into()),
        "json" => Some(tree_sitter_json::LANGUAGE.into()),
        "c" | "h" => Some(tree_sitter_c::LANGUAGE.into()),
        "cpp" | "c++" | "cc" | "hpp" => Some(tree_sitter_cpp::LANGUAGE.into()),
        "java" => Some(tree_sitter_java_orchard::LANGUAGE.into()),
        "csharp" | "cs" => Some(tree_sitter_c_sharp::LANGUAGE.into()),
        "bash" | "sh" => Some(tree_sitter_bash::LANGUAGE.into()),
        "ruby" | "rb" => Some(tree_sitter_ruby::LANGUAGE.into()),
        "php" => Some(tree_sitter_php::LANGUAGE_PHP.into()),
        "css" | "scss" => Some(tree_sitter_css::LANGUAGE.into()),
        "yaml" | "yml" => Some(tree_sitter_yaml::LANGUAGE.into()),
        "xml" | "html" => Some(tree_sitter_xml::LANGUAGE_XML.into()),
        "lua" => Some(tree_sitter_lua::LANGUAGE.into()),
        "scala" => Some(tree_sitter_scala::LANGUAGE.into()),
        "swift" => Some(tree_sitter_swift::LANGUAGE.into()),
        "elixir" => Some(tree_sitter_elixir::LANGUAGE.into()),
        "haskell" | "hs" => Some(tree_sitter_haskell::LANGUAGE.into()),
        "nix" => Some(tree_sitter_nix::LANGUAGE.into()),
        "zig" => Some(tree_sitter_zig::LANGUAGE.into()),
        "elm" => Some(tree_sitter_elm::LANGUAGE.into()),
        "fsharp" | "fs" => Some(tree_sitter_fsharp::LANGUAGE_FSHARP.into()),
        "ocaml" | "ml" => Some(tree_sitter_ocaml::LANGUAGE_OCAML.into()),
        "r" => Some(tree_sitter_r::LANGUAGE.into()),
        "julia" => Some(tree_sitter_julia::LANGUAGE.into()),
        "dart" => Some(tree_sitter_dart_orchard::LANGUAGE.into()),
        "clojure" | "clj" => Some(tree_sitter_clojure_orchard::LANGUAGE.into()),
        "toml" => Some(tree_sitter_toml_ng::LANGUAGE.into()),
        "sql" => Some(tree_sitter_sequel::LANGUAGE.into()),
        "cmake" => Some(tree_sitter_cmake::LANGUAGE.into()),
        "fish" => Some(tree_sitter_fish::language().into()),
        "make" | "makefile" => Some(tree_sitter_make::LANGUAGE.into()),
        "perl" | "pl" => Some(ts_parser_perl::LANGUAGE.into()),
        "proto" | "protobuf" => Some(tree_sitter_proto::LANGUAGE.into()),
        "racket" | "rkt" => Some(tree_sitter_racket::LANGUAGE.into()),
        "scheme" | "scm" => Some(tree_sitter_scheme::LANGUAGE.into()),
        "verilog" | "v" => Some(tree_sitter_verilog::LANGUAGE.into()),
        "vhdl" => Some(tree_sitter_vhdl::LANGUAGE.into()),
        "pascal" | "pas" => Some(tree_sitter_pascal::LANGUAGE.into()),
        "objc" | "objective-c" | "m" => Some(tree_sitter_objc::LANGUAGE.into()),
        _ => None,
    }
}
