"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.externalWorkspaceChangeNode = exports.decisionNode = exports.constitutionRuleNode = exports.constitutionCheckEdge = exports.completionValidationEdge = exports.completionNode = exports.checkpointNode = exports.approvalNodeID = exports.approvalNode = exports.approvalEdge = exports.agentActionNodeID = exports.agentActionNode = exports.LANDING_LOG_HEADING = exports.applyPlanDocTick = exports.projectPlanTaskStates = exports.parsePlanTasks = exports.evaluatePlanTaskState = exports.PATH_CLASS_EVIDENCE = exports.MINIMUM_EVIDENCE_MATRIX = exports.validateWorkContractFields = exports.isUnverifiableContract = exports.isPlaceholderContractValue = exports.evaluateCompletionCard = exports.classifyPathClass = exports.classifyTaskKind = exports.validateDetour = exports.mergeDetourIntoContract = exports.buildDetourReviewed = exports.buildDetourRequested = exports.buildWorkContractDrafted = exports.buildWorkContractAccepted = exports.createWorkLedgerController = exports.buildPlanDocUpdated = exports.buildPlanDocStatus = exports.buildPlanDocMarked = exports.buildPlanDocDeleted = exports.buildPlanDocCreated = exports.buildAuditRequested = exports.DRIFT_SIGNAL_WINDOW = exports.deriveDriftBehaviorSignals = exports.PROSE_RELEVANCE_THRESHOLD = exports.proseRelevanceQuestion = exports.targetDriftAbsorbedByScope = exports.pathInScope = exports.createDriftEvaluator = exports.buildDriftFindingUpdate = exports.buildDriftFinding = exports.DRIFT_FINDING_WRITER_OWNER = exports.DRIFT_CONTRACT_VERSION = exports.workLedgerController = void 0;
exports.workspaceChangeNodeID = exports.workspaceChangeNode = exports.verifyWorkGraphIntegrity = exports.unattributedChangeNodes = exports.workspaceChangeEdge = exports.WORK_GRAPH_KIND = exports.WORK_GRAPH_EDGE_KIND = exports.toolCallNodeID = exports.toolCallNode = exports.toolCallEdge = exports.rollbackCheckpointEdge = void 0;
__exportStar(require("./contracts"), exports);
__exportStar(require("./invariants"), exports);
var service_token_1 = require("./service-token");
Object.defineProperty(exports, "workLedgerController", { enumerable: true, get: function () { return service_token_1.workLedgerController; } });
var drift_evaluator_1 = require("./drift-evaluator");
Object.defineProperty(exports, "DRIFT_CONTRACT_VERSION", { enumerable: true, get: function () { return drift_evaluator_1.DRIFT_CONTRACT_VERSION; } });
Object.defineProperty(exports, "DRIFT_FINDING_WRITER_OWNER", { enumerable: true, get: function () { return drift_evaluator_1.DRIFT_FINDING_WRITER_OWNER; } });
Object.defineProperty(exports, "buildDriftFinding", { enumerable: true, get: function () { return drift_evaluator_1.buildDriftFinding; } });
Object.defineProperty(exports, "buildDriftFindingUpdate", { enumerable: true, get: function () { return drift_evaluator_1.buildDriftFindingUpdate; } });
Object.defineProperty(exports, "createDriftEvaluator", { enumerable: true, get: function () { return drift_evaluator_1.createDriftEvaluator; } });
Object.defineProperty(exports, "pathInScope", { enumerable: true, get: function () { return drift_evaluator_1.pathInScope; } });
Object.defineProperty(exports, "targetDriftAbsorbedByScope", { enumerable: true, get: function () { return drift_evaluator_1.targetDriftAbsorbedByScope; } });
Object.defineProperty(exports, "proseRelevanceQuestion", { enumerable: true, get: function () { return drift_evaluator_1.proseRelevanceQuestion; } });
Object.defineProperty(exports, "PROSE_RELEVANCE_THRESHOLD", { enumerable: true, get: function () { return drift_evaluator_1.PROSE_RELEVANCE_THRESHOLD; } });
var drift_signals_1 = require("./drift-signals");
Object.defineProperty(exports, "deriveDriftBehaviorSignals", { enumerable: true, get: function () { return drift_signals_1.deriveDriftBehaviorSignals; } });
Object.defineProperty(exports, "DRIFT_SIGNAL_WINDOW", { enumerable: true, get: function () { return drift_signals_1.DRIFT_SIGNAL_WINDOW; } });
var plan_registry_1 = require("./plan-registry");
Object.defineProperty(exports, "buildAuditRequested", { enumerable: true, get: function () { return plan_registry_1.buildAuditRequested; } });
Object.defineProperty(exports, "buildPlanDocCreated", { enumerable: true, get: function () { return plan_registry_1.buildPlanDocCreated; } });
Object.defineProperty(exports, "buildPlanDocDeleted", { enumerable: true, get: function () { return plan_registry_1.buildPlanDocDeleted; } });
Object.defineProperty(exports, "buildPlanDocMarked", { enumerable: true, get: function () { return plan_registry_1.buildPlanDocMarked; } });
Object.defineProperty(exports, "buildPlanDocStatus", { enumerable: true, get: function () { return plan_registry_1.buildPlanDocStatus; } });
Object.defineProperty(exports, "buildPlanDocUpdated", { enumerable: true, get: function () { return plan_registry_1.buildPlanDocUpdated; } });
var work_ledger_controller_1 = require("./work-ledger-controller");
Object.defineProperty(exports, "createWorkLedgerController", { enumerable: true, get: function () { return work_ledger_controller_1.createWorkLedgerController; } });
var work_contract_1 = require("./work-contract");
Object.defineProperty(exports, "buildWorkContractAccepted", { enumerable: true, get: function () { return work_contract_1.buildWorkContractAccepted; } });
Object.defineProperty(exports, "buildWorkContractDrafted", { enumerable: true, get: function () { return work_contract_1.buildWorkContractDrafted; } });
Object.defineProperty(exports, "buildDetourRequested", { enumerable: true, get: function () { return work_contract_1.buildDetourRequested; } });
Object.defineProperty(exports, "buildDetourReviewed", { enumerable: true, get: function () { return work_contract_1.buildDetourReviewed; } });
Object.defineProperty(exports, "mergeDetourIntoContract", { enumerable: true, get: function () { return work_contract_1.mergeDetourIntoContract; } });
Object.defineProperty(exports, "validateDetour", { enumerable: true, get: function () { return work_contract_1.validateDetour; } });
Object.defineProperty(exports, "classifyTaskKind", { enumerable: true, get: function () { return work_contract_1.classifyTaskKind; } });
Object.defineProperty(exports, "classifyPathClass", { enumerable: true, get: function () { return work_contract_1.classifyPathClass; } });
Object.defineProperty(exports, "evaluateCompletionCard", { enumerable: true, get: function () { return work_contract_1.evaluateCompletionCard; } });
Object.defineProperty(exports, "isPlaceholderContractValue", { enumerable: true, get: function () { return work_contract_1.isPlaceholderContractValue; } });
Object.defineProperty(exports, "isUnverifiableContract", { enumerable: true, get: function () { return work_contract_1.isUnverifiableContract; } });
Object.defineProperty(exports, "validateWorkContractFields", { enumerable: true, get: function () { return work_contract_1.validateWorkContractFields; } });
Object.defineProperty(exports, "MINIMUM_EVIDENCE_MATRIX", { enumerable: true, get: function () { return work_contract_1.MINIMUM_EVIDENCE_MATRIX; } });
Object.defineProperty(exports, "PATH_CLASS_EVIDENCE", { enumerable: true, get: function () { return work_contract_1.PATH_CLASS_EVIDENCE; } });
var plan_task_state_1 = require("./plan-task-state");
Object.defineProperty(exports, "evaluatePlanTaskState", { enumerable: true, get: function () { return plan_task_state_1.evaluatePlanTaskState; } });
Object.defineProperty(exports, "parsePlanTasks", { enumerable: true, get: function () { return plan_task_state_1.parsePlanTasks; } });
Object.defineProperty(exports, "projectPlanTaskStates", { enumerable: true, get: function () { return plan_task_state_1.projectPlanTaskStates; } });
Object.defineProperty(exports, "applyPlanDocTick", { enumerable: true, get: function () { return plan_task_state_1.applyPlanDocTick; } });
Object.defineProperty(exports, "LANDING_LOG_HEADING", { enumerable: true, get: function () { return plan_task_state_1.LANDING_LOG_HEADING; } });
var work_graph_1 = require("./work-graph");
Object.defineProperty(exports, "agentActionNode", { enumerable: true, get: function () { return work_graph_1.agentActionNode; } });
Object.defineProperty(exports, "agentActionNodeID", { enumerable: true, get: function () { return work_graph_1.agentActionNodeID; } });
Object.defineProperty(exports, "approvalEdge", { enumerable: true, get: function () { return work_graph_1.approvalEdge; } });
Object.defineProperty(exports, "approvalNode", { enumerable: true, get: function () { return work_graph_1.approvalNode; } });
Object.defineProperty(exports, "approvalNodeID", { enumerable: true, get: function () { return work_graph_1.approvalNodeID; } });
Object.defineProperty(exports, "checkpointNode", { enumerable: true, get: function () { return work_graph_1.checkpointNode; } });
Object.defineProperty(exports, "completionNode", { enumerable: true, get: function () { return work_graph_1.completionNode; } });
Object.defineProperty(exports, "completionValidationEdge", { enumerable: true, get: function () { return work_graph_1.completionValidationEdge; } });
Object.defineProperty(exports, "constitutionCheckEdge", { enumerable: true, get: function () { return work_graph_1.constitutionCheckEdge; } });
Object.defineProperty(exports, "constitutionRuleNode", { enumerable: true, get: function () { return work_graph_1.constitutionRuleNode; } });
Object.defineProperty(exports, "decisionNode", { enumerable: true, get: function () { return work_graph_1.decisionNode; } });
Object.defineProperty(exports, "externalWorkspaceChangeNode", { enumerable: true, get: function () { return work_graph_1.externalWorkspaceChangeNode; } });
Object.defineProperty(exports, "rollbackCheckpointEdge", { enumerable: true, get: function () { return work_graph_1.rollbackCheckpointEdge; } });
Object.defineProperty(exports, "toolCallEdge", { enumerable: true, get: function () { return work_graph_1.toolCallEdge; } });
Object.defineProperty(exports, "toolCallNode", { enumerable: true, get: function () { return work_graph_1.toolCallNode; } });
Object.defineProperty(exports, "toolCallNodeID", { enumerable: true, get: function () { return work_graph_1.toolCallNodeID; } });
Object.defineProperty(exports, "WORK_GRAPH_EDGE_KIND", { enumerable: true, get: function () { return work_graph_1.WORK_GRAPH_EDGE_KIND; } });
Object.defineProperty(exports, "WORK_GRAPH_KIND", { enumerable: true, get: function () { return work_graph_1.WORK_GRAPH_KIND; } });
Object.defineProperty(exports, "workspaceChangeEdge", { enumerable: true, get: function () { return work_graph_1.workspaceChangeEdge; } });
Object.defineProperty(exports, "unattributedChangeNodes", { enumerable: true, get: function () { return work_graph_1.unattributedChangeNodes; } });
Object.defineProperty(exports, "verifyWorkGraphIntegrity", { enumerable: true, get: function () { return work_graph_1.verifyWorkGraphIntegrity; } });
Object.defineProperty(exports, "workspaceChangeNode", { enumerable: true, get: function () { return work_graph_1.workspaceChangeNode; } });
Object.defineProperty(exports, "workspaceChangeNodeID", { enumerable: true, get: function () { return work_graph_1.workspaceChangeNodeID; } });
