"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createWorkspaceWriteLock = exports.turnCorrelation = exports.operationCorrelation = exports.observationHealth = exports.attributionFor = exports.assertSecretSafeObservation = exports.watchWorkspaceFiles = exports.searchWorkspaceFiles = exports.readWorkspaceFile = exports.listWorkspaceFiles = exports.invalidateWorkspaceFiles = exports.globWorkspaceFiles = exports.findWorkspaceFiles = exports.createWorkspaceFilesController = exports.createWorkspaceChangeAuditor = exports.createMutationRegistry = exports.workspaceWriteLock = exports.workspaceMutations = exports.workspaceFiles = void 0;
var service_tokens_1 = require("./service-tokens");
Object.defineProperty(exports, "workspaceFiles", { enumerable: true, get: function () { return service_tokens_1.workspaceFiles; } });
Object.defineProperty(exports, "workspaceMutations", { enumerable: true, get: function () { return service_tokens_1.workspaceMutations; } });
Object.defineProperty(exports, "workspaceWriteLock", { enumerable: true, get: function () { return service_tokens_1.workspaceWriteLock; } });
var mutation_registry_1 = require("./mutation-registry");
Object.defineProperty(exports, "createMutationRegistry", { enumerable: true, get: function () { return mutation_registry_1.createMutationRegistry; } });
var workspace_change_auditor_1 = require("./workspace-change-auditor");
Object.defineProperty(exports, "createWorkspaceChangeAuditor", { enumerable: true, get: function () { return workspace_change_auditor_1.createWorkspaceChangeAuditor; } });
var workspace_files_controller_1 = require("./workspace-files-controller");
Object.defineProperty(exports, "createWorkspaceFilesController", { enumerable: true, get: function () { return workspace_files_controller_1.createWorkspaceFilesController; } });
var platform_1 = require("@natalia/platform");
Object.defineProperty(exports, "findWorkspaceFiles", { enumerable: true, get: function () { return platform_1.findWorkspaceFiles; } });
Object.defineProperty(exports, "globWorkspaceFiles", { enumerable: true, get: function () { return platform_1.globWorkspaceFiles; } });
Object.defineProperty(exports, "invalidateWorkspaceFiles", { enumerable: true, get: function () { return platform_1.invalidateWorkspaceFiles; } });
Object.defineProperty(exports, "listWorkspaceFiles", { enumerable: true, get: function () { return platform_1.listWorkspaceFiles; } });
Object.defineProperty(exports, "readWorkspaceFile", { enumerable: true, get: function () { return platform_1.readWorkspaceFile; } });
Object.defineProperty(exports, "searchWorkspaceFiles", { enumerable: true, get: function () { return platform_1.searchWorkspaceFiles; } });
Object.defineProperty(exports, "watchWorkspaceFiles", { enumerable: true, get: function () { return platform_1.watchWorkspaceFiles; } });
var workspace_observation_1 = require("./workspace-observation");
Object.defineProperty(exports, "assertSecretSafeObservation", { enumerable: true, get: function () { return workspace_observation_1.assertSecretSafeObservation; } });
Object.defineProperty(exports, "attributionFor", { enumerable: true, get: function () { return workspace_observation_1.attributionFor; } });
Object.defineProperty(exports, "observationHealth", { enumerable: true, get: function () { return workspace_observation_1.observationHealth; } });
Object.defineProperty(exports, "operationCorrelation", { enumerable: true, get: function () { return workspace_observation_1.operationCorrelation; } });
Object.defineProperty(exports, "turnCorrelation", { enumerable: true, get: function () { return workspace_observation_1.turnCorrelation; } });
var workspace_write_lock_1 = require("./workspace-write-lock");
Object.defineProperty(exports, "createWorkspaceWriteLock", { enumerable: true, get: function () { return workspace_write_lock_1.createWorkspaceWriteLock; } });
