import { defineUiSkin, type UiSkin } from "@natalia/ui-kit";

export const nataliaLightSkin: UiSkin = defineUiSkin({
  id: "light",
  name: "Light",
  version: "1.0.0",
  tokens: {
    "--neu-bg": "#e8e9e1",
    "--neu-bg-light": "#f2f3ed",
    "--neu-bg-dark": "#1b1e24",
    "--neu-code-keyword": "#b85e9c",
    "--neu-code-string": "#2e8b57",
    "--neu-code-number": "#b06e2c",
    "--neu-code-function": "#2a7ab0",
    "--neu-code-class": "#7a4bb5",
    "--neu-code-property": "#2a7ab0",
    "--neu-shadow-dark": "rgba(48, 48, 46, 0.18)",
    "--neu-shadow-light": "rgba(255, 255, 255, 0.7)",
    "--neu-accent": "#8fb7b0",
    "--neu-accent-soft": "#b9d5cf",
    "--neu-text": "#30302e",
    "--neu-muted": "#7d8885",
    "--neu-success": "#6ba89f",
    "--neu-error": "#c9776b",
    "--neu-warning": "#b79549",
    "--neu-assistant-bubble": "#f2f3ed",
    "--neu-user-bubble": "#b9d5cf",
    "--neu-user-bubble-text": "#16201d",
    "--neu-user-bubble-border": "#b9d5cf",
    "--neu-border": "rgba(48, 48, 46, 0.12)",
    "--neu-hairline": "rgba(0, 0, 0, 0.06)",
    "--neu-overlay": "rgba(0, 0, 0, 0.25)",
    "--neu-overlay-scrim": "rgba(20, 22, 20, 0.35)",
    "--neu-hover-overlay": "rgba(48, 48, 46, 0.06)",
    "--neu-divider": "rgba(48, 48, 46, 0.12)",
  },
});

export const nataliaDarkSkin: UiSkin = defineUiSkin({
  id: "dark",
  name: "Graphite",
  version: "1.0.0",
  tokens: {
    "--neu-bg": "#1e1e20",
    "--neu-bg-light": "#28282b",
    "--neu-assistant-bubble": "#2c2c30",
    "--neu-bg-dark": "#1e1e20",
    "--neu-code-bg": "#34343c",
    "--neu-code-border": "#4a4a54",
    "--neu-code-text": "#6cb6ff",
    "--neu-code-keyword": "#d2a8ff",
    "--neu-code-string": "#7ee787",
    "--neu-code-number": "#d2a8ff",
    "--neu-code-function": "#6cb6ff",
    "--neu-code-class": "#f778ba",
    "--neu-code-property": "#6cb6ff",
    "--neu-shadow-dark": "rgba(0, 0, 0, 0.5)",
    "--neu-shadow-light": "rgba(255, 255, 255, 0.05)",
    "--neu-accent": "#6cb6ff",
    "--neu-accent-soft": "#d2a8ff",
    "--neu-text": "#e1e1e6",
    "--neu-muted": "#8c8c96",
    "--neu-success": "#7ee787",
    "--neu-error": "#e06c75",
    "--neu-warning": "#d2a8ff",
    "--neu-thinking": "#d2a8ff",
    "--neu-user-bubble": "#3b6ea5",
    "--neu-user-bubble-border": "#5b8fc0",
    "--neu-user-bubble-text": "#e1e1e6",
    "--neu-border": "#3a3a3e",
    "--neu-hairline": "rgba(225, 225, 230, 0.08)",
    "--neu-overlay": "rgba(0, 0, 0, 0.5)",
    "--neu-overlay-scrim": "rgba(0, 0, 0, 0.55)",
    "--neu-hover-overlay": "rgba(255, 255, 255, 0.04)",
    "--neu-divider": "rgba(225, 225, 230, 0.1)",
  },
});

export const NATALIA_SKINS: Record<string, UiSkin> = {
  light: nataliaLightSkin,
  dark: nataliaDarkSkin,
};

export const NEU_THEME_MODES = ["light", "dark"] as const;
export type NeuThemeMode = (typeof NEU_THEME_MODES)[number];
