"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.reconcilePlugins = exports.doctorPlugins = exports.resolveOfficialPluginPackage = exports.reinstallOfficialPlugin = exports.OFFICIAL_PLUGIN_PACKAGES = exports.initializeOfficialPlugins = exports.uninstallPlugin = exports.setPluginEnabled = exports.installPlugin = exports.listInstalledPlugins = exports.saveNataliaLock = exports.pluginClosurePaths = exports.packageDirectory = exports.loadNataliaLock = exports.nataliaLockSchema = void 0;
var contracts_1 = require("@natalia/contracts");
Object.defineProperty(exports, "nataliaLockSchema", { enumerable: true, get: function () { return contracts_1.nataliaLockSchema; } });
var closure_1 = require("./closure");
Object.defineProperty(exports, "loadNataliaLock", { enumerable: true, get: function () { return closure_1.loadNataliaLock; } });
Object.defineProperty(exports, "packageDirectory", { enumerable: true, get: function () { return closure_1.packageDirectory; } });
Object.defineProperty(exports, "pluginClosurePaths", { enumerable: true, get: function () { return closure_1.pluginClosurePaths; } });
Object.defineProperty(exports, "saveNataliaLock", { enumerable: true, get: function () { return closure_1.saveNataliaLock; } });
var catalog_1 = require("./catalog");
Object.defineProperty(exports, "listInstalledPlugins", { enumerable: true, get: function () { return catalog_1.listInstalledPlugins; } });
var lifecycle_1 = require("./lifecycle");
Object.defineProperty(exports, "installPlugin", { enumerable: true, get: function () { return lifecycle_1.installPlugin; } });
Object.defineProperty(exports, "setPluginEnabled", { enumerable: true, get: function () { return lifecycle_1.setPluginEnabled; } });
Object.defineProperty(exports, "uninstallPlugin", { enumerable: true, get: function () { return lifecycle_1.uninstallPlugin; } });
var official_1 = require("./official");
Object.defineProperty(exports, "initializeOfficialPlugins", { enumerable: true, get: function () { return official_1.initializeOfficialPlugins; } });
Object.defineProperty(exports, "OFFICIAL_PLUGIN_PACKAGES", { enumerable: true, get: function () { return official_1.OFFICIAL_PLUGIN_PACKAGES; } });
Object.defineProperty(exports, "reinstallOfficialPlugin", { enumerable: true, get: function () { return official_1.reinstallOfficialPlugin; } });
Object.defineProperty(exports, "resolveOfficialPluginPackage", { enumerable: true, get: function () { return official_1.resolveOfficialPluginPackage; } });
var maintenance_1 = require("./maintenance");
Object.defineProperty(exports, "doctorPlugins", { enumerable: true, get: function () { return maintenance_1.doctorPlugins; } });
Object.defineProperty(exports, "reconcilePlugins", { enumerable: true, get: function () { return maintenance_1.reconcilePlugins; } });
